import { ROLES } from './roles.js';

export const PERMISSIONS = {
  USERS_MANAGE: 'users.manage',
  STUDENTS_MANAGE: 'students.manage',
  BATCHES_MANAGE: 'batches.manage',
  ATTENDANCE_MANAGE: 'attendance.manage',
  FEES_MANAGE: 'fees.manage',
  REPORTS_VIEW: 'reports.view'
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ACADEMY_ADMIN]: ALL_PERMISSIONS,
  [ROLES.COACH]: [PERMISSIONS.STUDENTS_MANAGE, PERMISSIONS.BATCHES_MANAGE, PERMISSIONS.ATTENDANCE_MANAGE],
  [ROLES.MANAGER]: [PERMISSIONS.STUDENTS_MANAGE, PERMISSIONS.BATCHES_MANAGE, PERMISSIONS.REPORTS_VIEW],
  [ROLES.ACCOUNTANT]: [PERMISSIONS.FEES_MANAGE, PERMISSIONS.REPORTS_VIEW],
  [ROLES.VIEWER]: [PERMISSIONS.REPORTS_VIEW]
};
