import { ROLES } from './roles.js';

export const PERMISSIONS = {
  USERS_MANAGE: 'users.manage',
  STUDENTS_MANAGE: 'students.manage',
  BATCHES_MANAGE: 'batches.manage',
  ATTENDANCE_MANAGE: 'attendance.manage',
  FEES_MANAGE: 'fees.manage',
  REPORTS_VIEW: 'reports.view'
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.COACH]: [PERMISSIONS.STUDENTS_MANAGE, PERMISSIONS.BATCHES_MANAGE, PERMISSIONS.ATTENDANCE_MANAGE],
  [ROLES.STAFF]: [PERMISSIONS.STUDENTS_MANAGE, PERMISSIONS.ATTENDANCE_MANAGE]
};
